### ISSUE TITLE
Texcount not working in 1.2.5

### ISSUE THREAD

**Issue by minihessel** [LaTeXing/LaTeXing#101]
![screen shot 2015-02-25 at 16 40 57](https://cloud.githubusercontent.com/assets/5398823/6373769/26c93764-bd0d-11e4-88b1-c28b8952bb75.png)
I'm unable to use tex count after updating to 1.2.5, this is the log:

_LTX ERROR terminal.py:387 popen type object got multiple values for keyword argument 'env'_
_LTX ERROR terminal.py:388 popen /usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/usr/local/bin:/opt/local/bin:_
_LTX ERROR terminal.py:144 run local variable 'proc' referenced before assignment_
_error: Error while executing:_
_texcount -0 /Users/Eskil/Documents/MASTER_LATEX/main.tex_

**Comment by csch0** [comment]
Should be fixed in 1.2.6, please let me know.

**Comment by minihessel** [comment]
Still doesn't work,sorry
