### ISSUE TITLE
The package specified, oauthlib, is not available

### ISSUE THREAD

**Issue by N4M3Z** [LaTeXing/LaTeXing#106]
Is the package oauthlib suddenly gone from Package Control or am I the only one?

**Comment by csch0** [comment]
Nope its gone, so please uninstall it. Just make sure you are using the latest version of Package Control (3.0.1) and everything else should be installed automatically.

Perhaps you need to remove LaTeXing and install it again one more time to make sure everything is correct but normally Package Control installs all the required dependencies.

**Comment by N4M3Z** [comment]
I see. I had to manually remove the oauthlib package, somehow the dependency resolver insisted on looking for it.

**Comment by csch0** [comment]
Yes but this was not the dependency resolver it was the missing packages resolver I guess. Heard the same behavior from some other people too.

**Comment by N4M3Z** [comment]
Right, it was the *missing package resolver*, thank you for the correction. Thank you for your help and keep up the good work.
