### ISSUE TITLE
Please consider storing licence information in a separate file

### ISSUE THREAD

**Issue by N4M3Z** [LaTeXing/LaTeXing#107]
Please consider storing licence information in a separate file like LaTeXing.sublime-license (the way Sublimerge package does it). This would allow users to share settings while keeping only the license file protected (or better yet, encrypted via blackbox or vice versa).

**Comment by csch0** [comment]
Yes!!! Will do, just had some serious problem with Mendeley over the last
past weeks

**Comment by csch0** [comment]
same as #79
