### ISSUE TITLE
Bibtex not working when using output_directory=true

### ISSUE THREAD

**Issue by QuentinRoy** [LaTeXing/LaTeXing#115]
Well everything is in the title. I guess because all the aux files are actually moved in a separate directory, bibtex does not find what it needs anymore. Everything works fine without it.

As a workaround, i'm currently looking at the latexmk documentation to see if I can change the bibtex arguments, but I think it would be great if latexing could do that automatically as it really looks like a bug.

**Comment by QuentinRoy** [comment]
Oh, I think it may be the same problem than #17.

**Comment by csch0** [comment]
See #97
