### ISSUE TITLE
Parenthesis parsing bug in LaTeX formulas

### ISSUE THREAD

**Issue by iliyang** [LaTeXing/LaTeXing#122]
Hi,

I don't know if it's a bug in LaTeXing or some built-in LaTeX code parsing module, but when parentheses don't match in a formula, the syntax highlighting is screwed up. I think formulas should be parsed separately and not as part of the text, and no such parenthesis matching should be applied for them. Here's a simple example:

![image](https://cloud.githubusercontent.com/assets/802594/6666416/21231e5a-cbdc-11e4-971b-dd5b3413b60e.png)

The problem is that after this formula occurs in my text, the highlighting and the spell checking in rest of the entire document is screwed :(

**Comment by csch0** [comment]
This would be more a problem if the built in LaTeX code parsing and not LaTeXing but even there I cannot reproduce the problem with this easy example:

![screen shot 2015-03-16 at 20 35 55](https://cloud.githubusercontent.com/assets/3438979/6674741/1b337aae-cc1c-11e4-818d-5f0a040fc8a6.png)

Am I doing something wrong?

**Comment by iliyang** [comment]
Thanks for the reply! It turned out that it was a problem in my modified LaTeX highlighting files :-)
