### ISSUE TITLE
ST3 + latexing + SublimeKnitr + R-Box (new version of Enhanced-R) not working

### ISSUE THREAD

**Issue by Bozh** [LaTeXing/LaTeXing#125]
Hi,
    I’d like to thank you for the package. It provides a convenient way of using latex and knitr in sublime text 3. 
     I followed the instructions in this post closely, http://docs.latexing.com/stable/tutorials/knitr-with-latexing.html, but it does not work. Briefly, I came across the following problems:
   1) the syntax highlighting is not correct in Latexing(Knitr) (the code chunk is not highlighted, comment could not be recognized because symbol # is not recognized), as can be seen in the screenshot, 
![screen shot 2015-03-23 at 3 32 03 pm](https://cloud.githubusercontent.com/assets/7104410/6776301/b9a2089e-d177-11e4-89ac-e1766a29730a.png)
but it is correct when I choose the syntax to be knitr(Rnw) from package SublimeKnitr. But when I save the file,  it automatically changes back to Latexing(Knitr) and make the syntax highlighting wrong again. 
   2) The file cannot be “knitted”. 
![screen shot 2015-03-23 at 4 16 03 pm](https://cloud.githubusercontent.com/assets/7104410/6776317/f9b3f49c-d177-11e4-9fe1-3562866c386e.png)

 So it seems that such error comes from not recognising the code chunk. I googled for a while but cannot fix this problem.
    I’m using Mac with OS X 10.9.5, my R version is 3.1.2. Thanks in advance for any hint.

**Comment by csch0** [comment]
OK I just checked it. Its working, at first for the syntax please make sure after you installed it you close the view itself nut just restart sublime text.

The second one looks like LaTeXing does not create the real tex file. Make sure you enabled the knitr option in the settings and that you clean you output directory in case its still not working.

**Comment by Bozh** [comment]
Thanks for your reply. It seems now the syntax highlighting is correct. However, when I build the file, there is no error but the output is a .md file instead of a pdf. Did I miss anything here?
![screen shot 2015-03-26 at 3 08 02 pm](https://cloud.githubusercontent.com/assets/7104410/6841740/f47359b0-d3c9-11e4-94fb-6f77bd76708f.png)

**Comment by csch0** [comment]
Then you built system is wrong, that is nothing from LaTeXing (not even the
output I can see). Could you check your Sublime Console output and see
whats going on?

**Comment by Bozh** [comment]
Thanks for your guidance. I'll try figuring things out later.

**Comment by Bozh** [comment]
It works now. I just figure out the problem is that I missed the curly brackets in the package settings. Sorry for the naive newbie questions and thanks again.
