### ISSUE TITLE
No bibliography using apacite or default `plain` bibliography style (LaTeXing 1.2.9)

### ISSUE THREAD

**Issue by smithdanielle** [LaTeXing/LaTeXing#128]
When I try to compile a `.tex` file using `apacite` or the default `plain` style (see examples [here](https://sites.google.com/site/latexiseasy/bibliography)), I get messages saying `Citation [x] on page [y] undefined` for every citation in my document (Smith et al 2014 on page 1, for example). No `.aux` file is generated on the first pass (though it is for subsequent compiles), and no `.bbl` file is ever generated.

Everything works as expected (a) when I compile a `.bbl`file manually and then compile with Sublime Text/LaTeXing and (b) when I use other software, such as TeXworks, to compile.

Here's my system check:
```
+------------+----------+---------+---------------------------+
| Executable | Type     | Status  | Path                      |
+------------+----------+---------+---------------------------+
| perl       | required | Found   | perl                      |
| latexmk    | required | Found   | latexmk                   |
| texcount   | optional | Found   | texcount                  |
| biber      | optional | Found   | biber                     |
| bibtex     | optional | Found   | bibtex                    |
| pdflatex   | optional | Found   | pdflatex                  |
| xelatex    | optional | Found   | xelatex                   |
| lualatex   | optional | Found   | lualatex                  |
| kpsewhich  | optional | Found   | kpsewhich                 |
| texdoc     | optional | Found   | texdoc                    |
| sublime    | optional | Missing |                           |
| rscript    | optional | Found   | Rscript                   |
| preview    | viewer   | Found   | /Applications/Preview.app |
| skim       | viewer   | Found   | /Applications/Skim.app    |
+------------+----------+---------+---------------------------+

+----------------+
| Searched Path  |
+----------------+
| /usr/texbin    |
| /usr/sbin      |
| /sbin          |
| /usr/local/bin |
| /bin           |
| /usr/bin       |
| /opt/local/bin |
+----------------+
** Checked with LaTeXing 1.2.9
```

**Comment by csch0** [comment]
Thats odd indeed, but I think its a problem on your system since this would be a very essential problem. Whats your latexmk version?

**Comment by smithdanielle** [comment]
I agree, unfortunately I don't have another system I can check this on. I have tried removing and reinstalling everything, but that didn't help.

`latexmk` version is 4..43a.

**Comment by csch0** [comment]
Mmm, nope not sure how LaTeXTools works with this.

Do you have any settings set inside your LaTeX.sublime-settings? Like e.g.output_directory?

**Comment by smithdanielle** [comment]
I'm guessing you mean my `LaTeXing.sublime-settings`? The only thing I have in there is:

```
{"knitr": true}
```

**Comment by csch0** [comment]
Correct.. ok so lets enable the log mode, just add "log": true, restart sublime text and try it again. Then check the sublime text console view for any error, you can post it here or just sent an email to info@latexing.com

**Comment by smithdanielle** [comment]
Posted my console log dump [here](http://pastebin.com/raw.php?i=praXbuCe).

**Comment by csch0** [comment]
You can see you are just running pdflatex and not latexmk, therefore its clear that your bibliography is not created.

How do you try to build the file? The default behavior is to use latexmk, so perhaps you changed the LaTeX.sublime-build somehow?

**Comment by smithdanielle** [comment]
Aha! When I specify to build using `latexmk`, everything works as expected. As far as I can see, I don't have a `-build` file (it should be alongside the `-settings` file, right)?

In the `-settings` file `pdflatex` is the default build for some reason (I've never touched this file, so am a little confused as to why this is). How can I change the default behaviour -- should I create a `-build` file and insert:

```
"quick_build": [
        {
            "name": "Primary Quick Build: latexmk",
            "primary": true,
            "cmds": ["latexmk"]
        }
]
```

**Comment by csch0** [comment]
Can you not just press cmd + b to built the file, the setting you are talking about is more advanced to control the built process more in detail.

**Comment by smithdanielle** [comment]
When I do that, it uses `pdflatex` as that is the default quick build on my system. How can I change my default quick build? Do you have an example of what a `LaTeXing.sublime-build` file should look like (and where it should be placed)?

 I'm unsure as to why my default quick build is changed as it used to work fine (i.e. use `latexmk`) on an older system I had (running  LaTeXing < 1.2.9). When I installed it fresh on a new system a couple weeks ago it came with `pdflatex` as the default.

**Comment by csch0** [comment]
If you choose Build With: LaTeX its using latexmk by default

![screen shot 2015-04-10 at 11 42 55](https://cloud.githubusercontent.com/assets/3438979/7085403/bdd43d08-df76-11e4-8983-05ebbd04b315.png)

 I think you are using the latest Sublime Text 3 beta version or > 3080?

**Comment by smithdanielle** [comment]
That's true -- pressing `cmd + l` then `cmd + b` and choosing `Build With : LaTeX` works. However,  when I press `cmd + b` to build the file I get the options seen below:

![screen shot 2015-04-10 at 10 56 19](https://cloud.githubusercontent.com/assets/3224521/7085642/99782a6a-df70-11e4-9920-86febdb4fb7a.png)

On my older installation it just compiled using `latexmk` automatically when I pressed this key combination. I'm using ST3 Stable Build 3083.

**Comment by csch0** [comment]
Yes that this new feature of Sublime Text: Build System choices are remembered, so the user will be prompted to choose a build system less often

Just call cmd + shift + p (Command Palette) and choose the default build once. afterwards it should be set by default (hopefully). :)

**Comment by smithdanielle** [comment]
I'm not entirely sure what you mean by "choose the default build". I can choose `Build With: Choose Quick Build` and then specify `latexmk`, but when pressing `cmd + b` I'm still prompted to choose which build I want every time.

**Comment by csch0** [comment]
if you use cmd + l, cmd + b, thats a latexmk specific menu and not related with the built system. So you have so choose it from the default command palette.

**Comment by smithdanielle** [comment]
Even after choosing the build I want from the default command palette, I still have to choose my preferred build manually every time I press `cmd+b`. Two more keystrokes (`down + enter`)  makes all the difference ;).

However, using `shift+cmd+b` works, after changing my User setting files so that `latexmk` is the default... though it doesn't clean the temporary file for the current project as the documentation says it should. Odd.

Closing this issue now as my problem is essentially resolved. Thanks for your help!
