### ISSUE TITLE
Syntax Highlighting R Code

### ISSUE THREAD

**Issue by dougservice** [LaTeXing/LaTeXing#133]
I have started using LaTeXing with Sublime Text3 and like it very much so I purchased a license. I use it for both plain LaTeX and Knitr to combine LaTeX with R code. 

The highlighting for LaTeX is quite good, but the R text in a Knitr file is white. It would be very useful if the R code was also syntax highlighting.

**Comment by csch0** [comment]
@dougservice Enhanced-R/R-Box is not enough? Like explain here? http://docs.latexing.com/stable/tutorials/knitr-with-latexing.html

**Comment by csch0** [comment]
Will close this for now, if the problem still exists please reopen it.
