### ISSUE TITLE
Labels with parentheses do not get indexed appropriately for \ref{}

### ISSUE THREAD

**Issue by kathode** [LaTeXing/LaTeXing#134]
Hi there,

I have just been giving LaTeXing a trial to see whether it can replace my current LaTeX editor. 

I have a lot of labels in a large project with several .tex files, which often use parentheses in the label definition. Unfortunately, it seems that when using the lookup feature for the \cref{} command, the strings after any parentheses get erased. See the attached screenshot for an example.

![screen shot 2015-04-19 at 20 16 12](https://cloud.githubusercontent.com/assets/5167368/7220915/8f7f6f9c-e6d1-11e4-9bc2-282c0a4c089b.png)

This functionality is really crucial for my type of work, and I think it is not working as intended.

Thanks

**Comment by csch0** [comment]
Then indeed there is a problem, I think here it comes by your used names. Will add this as bug

**Comment by kathode** [comment]
Hi @csch0, is there any update on this bug? I would love to have this fixed in the near future.
