### ISSUE TITLE
Build system: Not recognizing citations from global .bib file

### ISSUE THREAD

**Issue by ZacharyST** [LaTeXing/LaTeXing#138]
I am using Latexing 1.2.9.  It's a huge improvement over TexShop - thanks for the great work! - but I can't get Latexing to work with my .bib file.  I use Mendeley for reference management and export all citations to a single .bib file.  

The .bib is a global one, not specific to any project, and it works fine when I use TexShop.  My user settings are:

{
"global_bib_file": "true",
"global_bib_file_path": "/Users/Zack/Documents/UCSD/Latex/Bibliography/library2/library.bib",
}

When I then choose Quick Build 1 (pdflatex, bib text, pdflatex x2), the document compiles with an error message for each citation.  Below is a sample:

W: /Users/Zack/Documents/UCSD/Dissertation/Papers/OverallTheory/ZST_Theory_Dissertation_v5.tex:0 File `Remote.bib` available but not included.
W: /Users/Zack/Documents/UCSD/Dissertation/Papers/OverallTheory/ZST_Theory_Dissertation_v5.tex:49 Citation 'Downs1957' on page 1 undefined
W: /Users/Zack/Documents/UCSD/Dissertation/Papers/OverallTheory/ZST_Theory_Dissertation_v5.tex:55 Citation 'Tullock1971' on page 2 undefined

Building pdflatex, bib text, and pdflatex x2 manually does not work.

I have also imported citations (cmd+l, cmd+r) but that does not change anything.  The ST3 terminal says: 

"
[Accessing library.bib]

Noting to import, all items are already available offline.

[Done]
“
after the import citations command.  A remote.bib file is then created in my project folder, but it is empty.  

I have also cleared my .bib cache, to no effect.  

Any help/guidance is much appreciated!

**Comment by smithdanielle** [comment]
Please see issues [#128](https://github.com/LaTeXing/LaTeXing/issues/128) and [#132](https://github.com/LaTeXing/LaTeXing/issues/132). Have you tried specifying a single build with latexmk?

I feel like this is a regression from previous behaviour -- the default used to use latexmk to build and the sublime executable **was** within the searched paths. Any idea why is this no longer the case?

**Comment by ZacharyST** [comment]
Hi smithdanielle, I just followed #128, but that did not help.  I did both cmd+l, cmd+b as well as using the command palette and selecting Build With: Latex.  I also updated my LaTeXing.sublime-settings to read:

{
	"global_bib_file": "true",
	"global_bib_file_path": ["/Users/Zack/Documents/UCSD/Latex/Bibliography/library2/library.bib"],
    "quick_build": [
        {
            "name": "Primary Quick Build: pdflatex",
            "primary": true,
            "cmds": ["latexmk"]
        },
        {
            "name": "Quick Build 1: pdflatex + bibtex + pdflatex (2x)",
            "cmds": ["latexmk", "bibtex", "latexmk", "latexmk"]
        },
        {
            "name": "Quick Build 2: pdflatex + biber + pdflatex (2x)",
            "cmds": ["latexmk", "biber", "latexmk", "latexmk"]
        }
    ],
}

Here is my system check: +------------+----------+---------+---------------------------+
| Executable | Type     | Status  | Path                      |
+------------+----------+---------+---------------------------+
| perl       | required | Found   | perl                      |
| latexmk    | required | Found   | latexmk                   |
| texcount   | optional | Found   | texcount                  |
| biber      | optional | Found   | biber                     |
| bibtex     | optional | Found   | bibtex                    |
| pdflatex   | optional | Found   | pdflatex                  |
| xelatex    | optional | Found   | xelatex                   |
| lualatex   | optional | Found   | lualatex                  |
| kpsewhich  | optional | Found   | kpsewhich                 |
| texdoc     | optional | Found   | texdoc                    |
| sublime    | optional | Missing |                           |
| rscript    | optional | Found   | Rscript                   |
| skim       | viewer   | Found   | /Applications/Skim.app    |
| preview    | viewer   | Found   | /Applications/Preview.app |

I linked the executable as in #132 and restarted ST3, but that did not change anything.

**Comment by csch0** [comment]
Yes that is all related to the "new" Sublime Text feature with the new build system. I will have to change that, will keep you updated @ZacharyST  and @smithdanielle. Thanks @smithdanielle for you help!

**Comment by ZacharyST** [comment]
Thank you!
