### ISSUE TITLE
inconsistent result of -pdfps build option

### ISSUE THREAD

**Issue by jaehyunp** [LaTeXing/LaTeXing#140]
Hi,

I'm trying to modify the default compile option to work with psfrag, for which I need to compile the tex file into dvi, ps, then to pdf. When I type the following command on console, I get the desired output with correct psfrag replacements:

```
latexmk -pdfps doc.tex
```

I modified relevant options in the settings file, and it compiles without an error, but psfrag doesn't work at all (no psfrag replacements).

```
"quick_build": [
        {
            "name": "Primary Quick Build: latexmk",
            "primary": true,
            "cmds": ["latexmk"]
        },
],
"build_arguments": [ "-pdfps" ],
```

If I change "-pdfps" to " -pdfps" or " --pdfps" (adding a space before hyphen), then I get the following error message:

```
Could not open log file, please check your system. Be sure you are using the latest version of your LaTeX distribution.
```

I'm very confused by what's happening, and would like to know why running latexmk with -pdfps option gives a different output from adding -pdfps option through the LaTeXing settings. Here's my environment.

OS: Windows 8.1
LaTeXing version: 1.2.9
latexmk version: 4.43a
Using MiKTeX 2.9 (with latest packages)

Thanks for the help in advance!

**Comment by jaehyunp** [comment]
I realized that latexing is calling latexmk with additional build options.
```
latexmk -pdfps -f -quiet -pdf -synctex=1 -jobname=doc ...
```
So the new question is, is it possible to customize this default build option? Specifically, I would like to disable the -pdf option. Adding -pdf- option doesn't help because it's overridden by -pdf.

**Comment by csch0** [comment]
Yes @jaehyunp you can do that inside of the LaTeX.sublime-build you know how to access this file??

**Comment by jaehyunp** [comment]
Thank you so much! I didn't know that this file existed. Problem is fixed now, but how about adding an additional note in latexing.sublime-settings?
