### ISSUE TITLE
Autocomplete problems in math mode

### ISSUE THREAD

**Issue by pzryumov** [LaTeXing/LaTeXing#141]
When editing a formula inside of the single $ sign, e.g., $\alp$ I get the autocomplete option option for \alpha, but upon pressing enter the cursor moves out of the $$ area and autocompletion is not occurring.

Is there a way to change this? I would rather have well working autocomplete then have a key binding for enter that moves the cursor outside of the $$.

**Comment by csch0** [comment]
Just press tab instead of enter and you stay inside the $$ signs.
