### ISSUE TITLE
New Beamer snippet

### ISSUE THREAD

**Issue by fredrikpaues** [LaTeXing/LaTeXing#142]
The New Beamer snippet file contains two (identical) `<snippet>` chunks. I can't see that this causes any problems, but it is ugly and easy to fix.

**Comment by csch0** [comment]
@fredrikpaues which file you are talking about? The "New Beamer" snippet looks like this for me:

```
<snippet>
    <content><![CDATA[
\documentclass{beamer}

\usepackage[english]{babel}
\usepackage[utf8]{inputenc}

\begin{document}

$1

\\end{document}
]]></content>
    <tabTrigger>documentclass{beamer}</tabTrigger>
    <scope>text.plain, text.tex.latex</scope>
    <description>New Beamer</description>
</snippet>
```

**Comment by fredrikpaues** [comment]
My bad. I just realized that I did something funny with the Package
Resource Viewer package. Sorry for the inconvenience.


________________________________________________
FREDRIK PAUES
a: Strindbergsgatan 51 (6tr), SE-115 53 Stockholm
e: fredrikpaues@gmail.com, m: +46 (0) 73 757 71 44

2015-05-03 10:10 GMT+02:00 csch0 <notifications@github.com>:
