### ISSUE TITLE
Access denied while accessing a global .bib file with relative path

### ISSUE THREAD

**Issue by DreaMeat** [LaTeXing/LaTeXing#143]
I have a global .bib exported from Zotero located in `~/Documents/zotero-library.bib`. I want to access this file from LaTeXing. I modified the settings as
```
{
    "global_bib_file": true,
    "global_bib_file_path": "~/Documents/zotero-library-bib"
}
```
When I try to access this file by the keybinding `C-l, C-r` I get the following error at the console.
```
[Accessing zotero-library-bib]

Checked global bibliography and access denied

[Done]
```
I'm using elementaryOS Freya (based on Ubuntu 14.04) and Sublime Text 3. 

Any help is appreciated.

**Comment by csch0** [comment]
@DreaMeat could you check if you are using the correct file name in your setting file. The file is named: zotero-library.bib but in the setting file you are using zotero-library-bib

**Comment by csch0** [comment]
Ok even without further details, I think this is related to the relative path of the bibliography file (#123).
