### ISSUE TITLE
Problem with installing LaTeXing on Scientific Linux 6.6

### ISSUE THREAD

**Issue by fibbo** [LaTeXing/LaTeXing#146]
I installed Sublime Text 3 64 bit Build 3083 from the tarball obtained here http://www.sublimetext.com/3. Using the Sublime Text console I installed the package control from which I then install LaTeXing. But then I have troubles - building doesn't work.

Under Tools - Package - LaTeXing for example almost everything is greyed out (exception are Settings - Default and Settings - User). For example I can't edit the Settings - Extended file. Also I can't enter my license key.

Now I'm not sure if this has something to do with the sublime version I'm using or a setting that I got wrong. I have Windows 8 at home and I also use ST3 it works without any problems.

**Comment by csch0** [comment]
Could be your Linux distribution... Don't know Scientific Linux yet but lets try to figure it out.. do you get any error message within your sublime text console while starting Sublime Text?

**Comment by fibbo** [comment]
Thats the log when I start ST3. http://pastebin.com/WB97YkdW

**Comment by csch0** [comment]
Yes as you can see the ssl module cannot be loaded which is required for the request plugin which comes with LaTeXing. Same like here https://github.com/LaTeXing/LaTeXing/issues/119#issuecomment-78929544, so looks like you have to update your glibc to make it work.

**Comment by fibbo** [comment]
Ah indeed... thanks for the quick help!
