### ISSUE TITLE
Custom syntax suggestion

### ISSUE THREAD

**Issue by aeonstone** [LaTeXing/LaTeXing#147]
My old eyes have trouble with the default syntax for misspelled words -- e.g. the squiggly line under the  incorrectly spelled word. Is there any way that I can change this to highlight the word using a custom color?

**Comment by csch0** [comment]
Not sure thats possible... perhaps you can try a different syntax style?!

**Comment by aeonstone** [comment]
Could I possibly change the Latex syntax style on my system?

**Comment by csch0** [comment]
I think the misspelling words style cannot be changed... you can change the style of course. Just check package control for available styles.

**Comment by aeonstone** [comment]
Oh well. Thanks for the response.
