### ISSUE TITLE
build results not hiding with badboxes and "show_log_panel_on" "infos"

### ISSUE THREAD

**Issue by drevicko** [LaTeXing/LaTeXing#148]
On ubuntu 12.04, sublime build 3083 LaTeXing1.2.9  if I add "infos" to the "show_log_panel_on" setting list, the build log appears when there are only badboxes present.

The end of the build log looks like this:

0 errors, 0 warnings, 38 badboxes

[Finished in 1.33s]

**Comment by csch0** [comment]
Yes but info (perhaps it should be renamed to always) means it will be shown always, so if you want to see only errors, warnings you have to add this:

```
show_log_panel_on: ["errors", "warning"]
```

**Comment by drevicko** [comment]
... that makes sense ... I could have sworn it behaved differently on Mac, but no, it's the same...
if it were 'all', it would have saved the confusion.. also a bit more sleep and less thesis anxiety!
apologies for cluttering your bug list, and thanks for taking the effort to reply!
