### ISSUE TITLE
Invalid cache data

### ISSUE THREAD

**Issue by MFairley** [LaTeXing/LaTeXing#150]
I am getting a popup error message whenever I type the first curly bracket in \usepackage{...}

"Invalid cache data, please reset the cache!"

![untitled tex sublime text today at 7 38 51 am](https://cloud.githubusercontent.com/assets/4374785/7688669/7be52946-fdfa-11e4-8328-c2bff1ec85bb.png)

**Comment by csch0** [comment]
Ok and anything else on the console?

**Comment by MFairley** [comment]
No, only this: "error: Invalid cache data, please reset the cache!"

**Comment by csch0** [comment]
Ok, could you please enable the log in the LaTeXing settings and try again... and check the console output.

**Comment by MFairley** [comment]
LTX DEBUG commands.py:322 run 12, 12
LTX DEBUG cache.py:178 is_cache_outdated pkg.cache 17.05.2015T23:24:11
error: Invalid cache data, please reset the cache!

**Comment by csch0** [comment]
Ok did you run the system check to see if everything can be found?

**Comment by MFairley** [comment]
Yes, I ran system check at the time I encountered the problem and everything was found. However, now the issue seems to have fixed itself.
