### ISSUE TITLE
High Power Consumption

### ISSUE THREAD

**Issue by zwerch** [LaTeXing/LaTeXing#154]
I don't really know how to describe this issue, but it seems that when I'm using Sublime with LaTeXing and editing a LaTeX document the power consumption of my MacBook Pro (13", Late 2013) kind of doubles. Looking at the activity monitor reveals nothing unusual high or something.
I didn't experience this with a few different Markdown compiler plugins, and of course I don't build every few seconds.
I already tried to reinstall the plugin, but this didn't help.
Is there some kind of watcher or similar that could cause this? Am I the only one so far noticing this?
I normally wouldn't care, but I've been editing some documents a few times away from a charger in the last few weeks, and it really bothered me having only half of the time.

**Comment by csch0** [comment]
Nope there is nothing, if you not build just the cache is updated from time to time. But if you are not working with 500 files per project that is negligible.

I am working most of the times on battery and never had an issue so far. So perhaps its a different plugin together with LaTeXing. If you can provide more informations please feel free to reopen this issue.
