### ISSUE TITLE
\ref not working

### ISSUE THREAD

**Issue by jotomicron** [LaTeXing/LaTeXing#157]
When I type `\ref{`, the dropdown with the possible labels does not show up.
I'm not sure where in my setup is this error coming from: I have a root document named "main.tex" and several files from 2 other directories ("content/" and "frontmatter/") that I `\include`. If I type

    \label{ABC} \ref{

in "main.tex", the ABC label is suggested. But if I type exactly the same thing in "content/file.tex", no suggestion is presented.

**Comment by iamrecursion** [comment]
I've had some issues with \ref in multi-part documents myself. Working in a sub-file, for me, has it only suggesting references from the parent file, not all other included files in a project. 

I'm not sure this is directly related, but thought it may be worth mentioning just in case.

**Comment by csch0** [comment]
@jotomicron, @iamrecursion please sent a minimum non working example at info@latexing.com

**Comment by iamrecursion** [comment]
Minimum non-working example sent.

**Comment by csch0** [comment]
Thanks @iamrecursion. You are using \include*{filename} instead of \include{filename}, is that even a valid command?? If I remove the star everything works fine

**Comment by iamrecursion** [comment]
You're correct that everything works fine if I remove it. `\include*{filename}` is a correct command as a component of `newclude`. It provides the functionality of `\include` without the page breaks (similar to `\input` but with the additional behaviour of `\include`).

**Comment by csch0** [comment]
Thanks @iamrecursion, created #159 for this

**Comment by iamrecursion** [comment]
Perfect! Thanks.

**Comment by csch0** [comment]
This issue will stay open until @jotomicron comes back with an example, perhaps he is coincidentally using the same command.

**Comment by jotomicron** [comment]
Ah, thanks for waiting for me.

From this discussion, I assume that latexing parses the root document for `\include` commands (and its cousins). However, I am using a custom include command that I need, since I have a bunch of macros that I want to call at the beginning of each chapter. I'm doing something similar to this:

    \newcommand\addfile[2][default]{
        % Use the default argument #1 in some way
        \include{#2}
        % Again use #1
    }

Is there any way to:

1. Tell latexing that `\addfile` is an `\include`-like command that takes an optional argument and then the name of the file to include;
2. Tell latexing that all files inside my tree need to be searched for labels; or
3. Tell latexing (by means of options) what my included files are?

I suspect 1. above is way to difficult, and 3. is a bit non-scalable, since I will need to add `\addfile{content/file}` to my root document and `"content/file.tex"` to the list of files to include. Point 2., however, seems like a good compromise. Is this possible (either at the moment or in future)?

**Comment by csch0** [comment]
Thanks @jotomicron for your reply. Thats indeed the problem but not a bug of LaTeXing in this context.

1. Thats not complicated to adjust but adding a custom tag and in your case the second argument as filename is not very generic. That is not maintainable.
2. Not an option for big projects. I am sure you don't want to reference a label which does not even exists in your current document
3. Not ideal, since you have to maintain multiple file list for your includes.

So I cannot see a generic solution here which I would like to implement. At the current stage I cannot see a good solution here which will beneficial for the mass-market.

**Comment by jotomicron** [comment]
1. Yes, that's what I meant by "too difficult". Doing something generic that would work in this situation is not really possible.
2. I did not consider the same directory to have more than one document. That would indeed be problematic. But how would one do this, if we only have one root tex file?

Anyway, thank you. I will think of a solution for my problem that feels right to me. I'm closing the Issue.
