### ISSUE TITLE
Allow changing the name of the "Output" directory

### ISSUE THREAD

**Issue by jotomicron** [LaTeXing/LaTeXing#160]
I like my directory structures to be neatly organised. Having latexing storing the output files of latex in "Output/" is great for this, but I would prefer if I could name this directory as I want. AFAICT this is hard-coded into latexing. Can we have an option to change the name of the output directory?

**Comment by csch0** [comment]
This could be changed but if you would like to keep your project folder clean just use output_directory_mode = 2 http://docs.latexing.com/stable/settings.html#output-directory

**Comment by jotomicron** [comment]
Thanks.

Why 2? The documentation on that option says either 0 for "Output" or 1 for a temporary directory (which is written as "dictionary", in fact).

**Comment by csch0** [comment]
Ups typo, sorry! I meant 1. :+1:

**Comment by jotomicron** [comment]
Oh, thanks :)

**Comment by jotomicron** [comment]
Unfortunately, I just tried this and the solution is not 100% functional. LaTeX will want to create the file content/file.aux but the directory "content" does not exist in the temporary directory and so compiling the source fails.

**Comment by csch0** [comment]
Perhaps you are using an oldish version of latexmk. I always use that by myself and therefore I am relatively sure that it's not failing in general.
