### ISSUE TITLE
generating a section label (ctrl-L ctrl-L) failing

### ISSUE THREAD

**Issue by drevicko** [LaTeXing/LaTeXing#161]
(Latexing 1.2.14 in ST3 on osx 10.8.5)
After positioning the cursor within the qoes "Overview" in \section{Overview} and pressing ctrl-L ctrl-L (to generate a \label{...}), I get the following in the console (and nothing happens in the text):

LTX DEBUG fill.py:63 run dicCommandRange: {'point': 1302, 'start': 1290, 'end': 1308}
LTX DEBUG fill.py:64 run dicCommand: {'name': 'section', 'arguments': [{'pair': '{', 'start': 1299, 'content': 'Overview', 'end': 1307}]}
LTX DEBUG fill.py:65 run dicArgument: {'argument': {'pair': '{', 'start': 1299, 'content': 'Overview', 'end': 1307}, 'pos': 0}
LTX INFO fill.py:101 run file_path: /Users/drevicko/Dropbox/phd_stuff/thesis/5-TopicModelsAsQuantitativeTool.tex
LTX INFO fill.py:102 run file_dir: /Users/drevicko/Dropbox/phd_stuff/thesis
LTX INFO fill.py:103 run file_name: 5-TopicModelsAsQuantitativeTool.tex
LTX INFO fill.py:104 run tex_path: /Users/drevicko/Dropbox/phd_stuff/thesis/thesis.tex
LTX INFO fill.py:105 run tex_dir: /Users/drevicko/Dropbox/phd_stuff/thesis/thesis.tex
LTX INFO fill.py:106 run tex_name_root: thesis
LTX INFO fill.py:107 run tex_name_ext: .tex
LTX INFO fill.py:108 run pdf_name_root: thesis
LTX INFO fill.py:109 run output_dir: False
LTX DEBUG fill.py:149 run rexChapter matched
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'newLine'

**Comment by dgraziotin** [comment]
Confirmed on OS X 10.10.4, ST3 beta.

**Comment by csch0** [comment]
Indeed, fixed in 1.2.15, will be released very soon.

**Comment by drevicko** [comment]
I can confirm it's fixed on my setup. Thx (:
