### ISSUE TITLE
Reloading package all the time

### ISSUE THREAD

**Issue by knonn** [LaTeXing/LaTeXing#162]
Hi there !
When I type a letter on a LaTeX document using LaTeXing language, the console show a "reloading Packages/user/latexing.sublime-settings" every letters I type.
This slow down sublime text (v3 latest build).
![capture du 2015-06-29 14 44 39](https://cloud.githubusercontent.com/assets/7189626/8408096/841967e2-1e6d-11e5-91f6-84097aea83c7.png)

How can I fix this ? Thank you.

**Comment by csch0** [comment]
Indeed not nice, know the reason. Will fix that in the next version

**Comment by N4M3Z** [comment]
I can confirm this:
```
reloading Packages/User/LaTeXing.sublime-settings
reloading Packages/User/LaTeXing.sublime-settings
reloading Packages/User/LaTeXing.sublime-settings
...
```

I wonder if this has to do with the performance issues I am experiencing with LaTeXing. Basically, I cannot type a sentence without the cursor getting stuck and this happens on high-end machine. Does not seem to be caused by any other package. Suggestions?

**Comment by csch0** [comment]
This is a bug which came together with 1.2.9, so not long ago. Fixed it already, will push the new version this week.

@N4M3Z how perhaps thats because your cache files are huge, could you check that? Could you enabled the LaTeXing log, restart Sublime Text and post your console output? Thanks

**Comment by N4M3Z** [comment]
Thanks for the quick response. The cache was not that huge:
```
LTX INFO cache.py:132 save doc.cache (44.0 bytes)
LTX INFO cache.py:132 save pkg.cache (62.4 KB)
LTX INFO cache.py:132 save tex.cache (402.4 KB)
LTX INFO cache.py:132 save citeulike.cache (55.0 bytes)
LTX INFO cache.py:132 save mendeley.cache (218.6 KB)
```
I tried to rebuild it (hard) but didn't see any improvement. Basically, what happens that while I type a single sentence, the cursor gets stuck multiple times and console repeatedly keeps printing this:
```
Package Syncing: Updated /Users/mzeman/Dropbox/Apps/Sublime Text/Character Table/Default/Default.sublime-keymap
Package Syncing: End Complete Sync
Package Control: No updated packages
LTX DEBUG completions.py:91 on_query_completions skip {'tag': '\\newcommand{\\PathImages}', 'line': 22, 'arguments': ['{:\\PathImages']}
LTX DEBUG completions.py:91 on_query_completions skip {'tag': '\\newcommand{\\PathTikz}', 'line': 23, 'arguments': ['{:\\PathTikz']}
LTX DEBUG completions.py:91 on_query_completions skip {'tag': '\\newcommand{\\PathImages}', 'line': 22, 'arguments': ['{:\\PathImages']}
LTX DEBUG completions.py:91 on_query_completions skip {'tag': '\\newcommand{\\PathTikz}', 'line': 23, 'arguments': ['{:\\PathTikz']}
UnicodeMath: 
reloading Packages/User/LaTeXing.sublime-settings
```
The `on_query_completions` gets called only when I type `\`. Perhaps this is an autocomplete issue? I understand that this is probably an issue with my setup, so thank you very much for taking the time to help me investigate this. I will try to go and disable every single package to find the culprit. I will let you know, perhaps it will be useful for some users.

**Comment by csch0** [comment]
Thanks for your research. Does the problem even exists for a minimal LaTeX example?

**Comment by N4M3Z** [comment]
I was pretty sure I could determine what is going on by turning off package after package. Turns out it is hard to determine where the problem is as Sublime Text just seems to be getting progressively (and unsuprisingly) slower the more packages are active. At some point, keyboard input into files handled by `LaTeXing` starts to get laggy. It could well be a problem with a number of packages running. Is there perhaps a way to monitor what is happening on key stroke? The problem is exclusively limited to files handled by `LaTeXing`. I guess I should start a separate issue for this?

**Comment by csch0** [comment]
@N4M3Z yes please, and could you also post a list of the used packages so I can try to verify the problem. Thanks!
