### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by N4M3Z** [LaTeXing/LaTeXing#164]
This is a followup on the performance issues mentioned in #162. Given a high number of packages installed in Sublime Text there is a highly laggy keyboard input into files handled by `LaTeXing`. I tried turning off other packages but could not determine the origin of the problem. It seems that disabling about 50% of my packages "solves" the issue. I cannot reproduce this for syntaxes handled by different packages (like `.py`) and it is unlikely that the issue is caused by linting (I tried turning it off). The following is a list of packages I am using:
```
	"installed_packages":
	[
		"Advanced CSV",
		"Alignment",
		"All Autocomplete",
		"Anaconda",
		"AngularJS",
		"ApplySyntax",
		"AutoDocstring",
		"BracketHighlighter",
		"BufferScroll",
		"Character Table",
		"CMake",
		"Color Highlighter",
		"Colorcoder",
		"ColorPicker",
		"CTags",
		"DashDoc",
		"DataConverter",
		"Dictionaries",
		"DocBlockr",
		"Emmet",
		"Evernote",
		"File History",
		"File Navigator",
		"FileBrowser",
		"FuzzyFilePath",
		"Gist",
		"Github Tools",
		"Gitignore",
		"Glue",
		"HexViewer",
		"Highlighter",
		"HTML-CSS-JS Prettify",
		"HTMLAttributes",
		"LaTeX-cwl",
		"LaTeXing",
		"Mako",
		"Markdown Preview",
		"MarkdownEditing",
		"MongoExec",
		"Package Control",
		"Package Syncing",
		"PackageResourceViewer",
		"PlainTasks",
		"Preference Helper",
		"Preferences Editor",
		"Project Manager",
		"Schemr",
		"SFTP",
		"SideBarEnhancements",
		"SublimeCodeIntel",
		"SublimeGit",
		"SublimeLinter",
		"SublimeLinter-chktex",
		"SublimeLinter-contrib-bootlint",
		"SublimeLinter-cppcheck",
		"SublimeLinter-csslint",
		"SublimeLinter-html-tidy",
		"SublimeLinter-javac",
		"SublimeLinter-jshint",
		"SublimeLinter-json",
		"SublimeLinter-lua",
		"SublimeLinter-php",
		"SublimeLinter-pylint",
		"SublimeLinter-ruby",
		"SublimeLinter-shellcheck",
		"Sublimerge Pro",
		"SVN",
		"Swift",
		"Terminal",
		"tern_for_sublime",
		"Theme - Cobalt2",
		"Theme - Flatgrammer",
		"Theme - Fox",
		"Theme - Gravity",
		"Theme - Lyte",
		"Theme - Piatto",
		"Theme - Soda",
		"Theme - Spacegray",
		"Themr",
		"TrailingSpaces",
		"UnicodeMath",
		"VCS Gutter",
		"View In Browser"
	],
```
The issue can be reproduced using a LaTeX MWE provided the file is saved. The lag occurs about every 20 characters on my machine (MacBook Pro 2011, i7 2.2 GHz, 16 GB RAM). Please let me know if I can help with this in any way.

**Comment by csch0** [comment]
A lot of packages..., Sublime Text was on my machine basically unusable (MacBook Air 2013). So you have null performance issues if LaTeXing is disabled?

To see if LaTeXing is really the reason on your system, what I don't think tbh, I could sent you a testing version with disabled keyboard listener to see if that helps.

**Comment by N4M3Z** [comment]
For files handled by `LaTeXing` (`.tex`, `.tikz` etc.) the performance is suboptimal to say the least. However, I regularly write in Python, C++, JS, HTML and all is well even with linters running realtime. It must be some kind of keyboard input listener, as you mentioned. I am all up for testing, thank you very much for taking time to help me with this.

**Comment by csch0** [comment]
ok, then we go with the testing version to see if we can improve this. Could you drop an email at info@latexing.com and I will sent you back a new package file.

Thanks for testing.

**Comment by N4M3Z** [comment]
Done

**Comment by sdrobert** [comment]
Dunno if this should be separate, but I *think* there's a memory leak. When I run sublime text with other plugins (including a linter), memory usage stays around 2.2%. However, as I type away in LaTeXing, memory usage slowly rises. I spent less than a minute typing "a" then backspace, and ST took another 2% memory.

My version is 1.2.14

**Comment by N4M3Z** [comment]
Dear csch0, did you send the testing package file? I did not receive any reply to my email to info@latexing.com.

**Comment by csch0** [comment]
Yes indeed but I pushed a new version (1.2.15) which removes almost everything during the keyboard listener. There will be no license check and/or popup anymore.

**Comment by N4M3Z** [comment]
I can confirm that there is a significant improvement with this release. Thank you.

**Comment by csch0** [comment]
Thanks @N4M3Z
