### ISSUE TITLE
Processor spikes after installing the license

### ISSUE THREAD

**Issue by MathieuNls** [LaTeXing/LaTeXing#165]
Hi,

I was using LaTeXing in trial mode for over a month and decided that your tool was worth its price and bought a license.

Since I've installed my license, my whole ST is subject to processor spike when I build, save or even browse the menu bar. One of my core goes up to 100% for 1 or 2 seconds every time.

M.

**Comment by MathieuNls** [comment]
I did more digging and it seems that while my project didn't grow that much between the before and the after of license I do spent a LOT more time on it.

I've noticed a gradual increase of the ST memory, until it reaches 100% and become unusable. Killing ST and relaunching "resolve" the problem. 

This issue could be the same as #164.

**Comment by csch0** [comment]
Should be gone in v1.2.15
