### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by reyman** [LaTeXing/LaTeXing#166]
I have only plugin actually, latexing, and it seems there is a memory leak, because memory rise slowly until ST crash or become inusable.
I'm using ST3 on ubuntu 14.10.

**Comment by csch0** [comment]
could you please check 1.2.15, and if the problem still exists please give me some number on how fast the memory rises. Do you have any other plugin enabled? If so please remove them to make sure the problem comes from LaTeXing.

**Comment by reyman** [comment]
it's ok now :)
