### ISSUE TITLE
Build does not work in El Capitan (OSX 10.11)

### ISSUE THREAD

**Issue by rudvfaden** [LaTeXing/LaTeXing#173]
In the beta version of 10.11 the build system does not work. Even after changing the path from `usr/texbin` to `library/tex/texbin` as suggested by [this](https://tug.org/mactex/UpdatingForElCapitan.pdf) it does not build correctly.

**Comment by rudvfaden** [comment]
Found out the build error was due to a font problem not. When fixed everything worked with the corrected path.

**Comment by rorymullen** [comment]
I think I'm in the same boat—just upgraded to OS X 10.11 (El Capitan), and now get the following error message when I build: "The command line tool "latexmk" is not available on your path. Please check your settings."

Where exactly did you change the path to library/tex/texbin? I've tried adding the following to the user settings file: "path":  "/Library/TeX/texbin". Still get the error.

**Comment by kopsta** [comment]
@rudvfaden 
I got the same problem as @rorymullen.
Did you work any black magic to make the changes? :D 
I noticed that if your check your system after you already changed the path, it still searches in the **wrong** path.

**Comment by csch0** [comment]
You simple have to add the bin path to the path settings in LaTeXing.

Since I got this question now a couple of times I will add a short tutorial to the homepage.

**Comment by kopsta** [comment]
Ahh.. got it! Works marvellous again.
`"path": ["/Library/TeX/texbin"]`
I think the main problem here is, that the solution is simpler than expected.
But yes a little guide would be great, since tomorrow is the official release of El Capitan.

**Comment by jvcasill** [comment]
Has a short tutorial been added to the homepage? I don't see it and I not able to correct this problem.

**Comment by joshmaxsilverman** [comment]
@kopsta where did you put ```"path": ["/Library/TeX/texbin"]```? I've added it to ```LaTeXing.sublime-setting``` but no luck.

**Comment by HakanSiktas** [comment]
@joshmaxsilverman Make sure to add them into your "Settings - User" configuration file within the Package Settings. If the file is empty, make sure to add brackets at the start and the end just like in Default settings file.

**Comment by joshmaxsilverman** [comment]
This is what my Settings - User config file currently looks like. Can you see any mistakes?

```{"osx":  {
        // Path used when invoking tex & friends; MUST include $PATH
        "texpath" : "$PATH:/usr/local/bin:/opt/local/bin:/Library/TeX/texbin/",
        "path": ["/Library/TeX/texbin"]
        // Path to PDF viewer, if needed
        // TODO think about it. Also, maybe configure it here!
    },
}```

**Comment by HakanSiktas** [comment]
The "osx" part should not be necessary. Something simple like this should be enough:

```
{
    "path": ["/Library/TeX/texbin"]
}

```

**Comment by joshmaxsilverman** [comment]
@HakanSiktas my man!

**Comment by pavelk2** [comment]
If for some people the following solution does not work:
```
{
    "path": ["/Library/TeX/texbin"]
}
```
Check where your texbin folder is. I checked and edited for:
```
{
	"path": ["/Library/TeX/Distributions/Programs/texbin"]
}

```
It works for me well.

**Comment by Meekohi** [comment]
Answer by @pavelk2 worked for me!
