### ISSUE TITLE
can't rebuild cache

### ISSUE THREAD

**Issue by TsumiNa** [LaTeXing/LaTeXing#177]
I use latexing 1.2.16 with ST3 3083 on windows8.1

when I compiled project, I got this notification. 
![capture](https://cloud.githubusercontent.com/assets/6410921/9107321/5752a162-3c61-11e5-9277-c2b2c76e7ff0.PNG)

if I pushed `Synchronise`, then got this
![capture2](https://cloud.githubusercontent.com/assets/6410921/9107402/e6d8aafc-3c61-11e5-972e-2e08ef80513c.PNG)

even I do it manually by `Rebuild cache` form `Ctrl+shift +P`, I got a error `error: The cache is already rebuilding, please wait!`
![capture2](https://cloud.githubusercontent.com/assets/6410921/9107274/0035a29e-3c61-11e5-9fcd-9c5e57189f31.PNG)

I deleted *.cache manually but didn't  worked! please help me, I can't work!

![capture](https://cloud.githubusercontent.com/assets/6410921/9107270/faf9574e-3c60-11e5-869c-afd142a63e9c.PNG)
![capture1](https://cloud.githubusercontent.com/assets/6410921/9107272/fd69dbb6-3c60-11e5-9fa5-2edec22a94f9.PNG)

**Comment by csch0** [comment]
Could you please provide the console log as well? Please reopen the issue in case the problem persists.
