### ISSUE TITLE
Opening a .tex file makes the focus jump to the pdf

### ISSUE THREAD

**Issue by WillyWinkel** [LaTeXing/LaTeXing#179]
I have a project with my text split over multiple source files.
Now every time I jump from one source to the other sublime vanishes and the pdf comes on top.
Specially when both sublime and preview are in Fullscreen something is broken here, since first the view (or active screen) jumps to the pdf, and then to the next normal desktop.

Would be awesome if there could be a way of turning that jumping off.
Or maybe just after compile.
Thank you for your time.

**Comment by csch0** [comment]
Just disable the following setting: http://docs.latexing.com/stable/settings.html#open-pdf-on-load

**Comment by WillyWinkel** [comment]
that was easy, thanks a lot.
