### ISSUE TITLE
Can build but not with Ctrl+B

### ISSUE THREAD

**Issue by fredrikpaues** [LaTeXing/LaTeXing#185]
Hi! I'm using a Windows 7 machine and Sublime 3083. When I press `Ctrl+Shift+B` then I can build just fine. But `Ctrl+B` causes an error message 'The command line tool "latexmk" is not available on your path. Please check your settings.' When I use the LaTeXing command "Check system" it says that Perl, latexmk and texcount are all missing, which seems odd to me since they are all installed and in the path.

**Comment by csch0** [comment]
ok.. I guess it was working before? pdflatex etc are available?

**Comment by csch0** [comment]
Just checked it with a fresh installation and no problem on my system, make sure the path is really listed at the bottom if the "Check system" and if not please add it using the LaTeXing setting path.

**Comment by fredrikpaues** [comment]
I don't know if it has ever worked on this computer. It is new to me.

Out of the executables listed in the "Check system" output, it is only `perl`, `latexmk`, `texcount` and `rscript` that are missing. 

The necessary paths for `perl`, `latexmk` and `texcount` should all be in the path:

    +------------------------------------------------------------------------+
    | Searched Path                                                          |
    +========================================================================+
    | C:\MikTeX\miktex\bin                                                   |
    +------------------------------------------------------------------------+
    | c:\Program Files (x86)\Intel\iCLS Client\                              |
    +------------------------------------------------------------------------+
    | c:\Program Files\Intel\iCLS Client\                                    |
    +------------------------------------------------------------------------+
    | C:\Windows\system32                                                    |
    +------------------------------------------------------------------------+
    | C:\Windows                                                             |
    +------------------------------------------------------------------------+
    | C:\Windows\System32\Wbem                                               |
    +------------------------------------------------------------------------+
    | C:\Windows\System32\WindowsPowerShell\v1.0\                            |
    +------------------------------------------------------------------------+
    | C:\Windows\System32\WindowsPowerShell\v1.0\                            |
    +------------------------------------------------------------------------+
    | C:\Program Files\Intel\Intel(R) Management Engine Components\DAL       |
    +------------------------------------------------------------------------+
    | C:\Program Files\Intel\Intel(R) Management Engine Components\IPT       |
    +------------------------------------------------------------------------+
    | C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL |
    +------------------------------------------------------------------------+
    | C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT |
    +------------------------------------------------------------------------+
    | C:\Strawberry\perl\bin                                                 |
    +------------------------------------------------------------------------+
    | C:\Strawberry\perl\site\bin                                            |
    +------------------------------------------------------------------------+
    | C:\Strawberry\c\bin                                                    |
    +------------------------------------------------------------------------+
    | C:\Dwimperl\perl\bin                                                   |
    +------------------------------------------------------------------------+
    | C:\Dwimperl\perl\site\bin                                              |
    +------------------------------------------------------------------------+
    | C:\Dwimperl\c\bin                                                      |
    +------------------------------------------------------------------------+
    | C:\Program Files\MATLAB\R2014b\runtime\win64                           |
    +------------------------------------------------------------------------+
    | C:\Program Files\MATLAB\R2014b\bin                                     |
    +------------------------------------------------------------------------+
    | C:\MiKTeX\miktex\bin\                                                  |
    +------------------------------------------------------------------------+
    | C:\Anaconda                                                            |
    +------------------------------------------------------------------------+
    | C:\Anaconda\Scripts                                                    |
    +------------------------------------------------------------------------+

However, when I try to run `perl`, `latexmk` and `texcount` from the command prompt I get the error message "The application was unable to start correctly (0xc000007n). Click OK to close the application." Could that be the problem?

**Comment by csch0** [comment]
Yes sure, please make sure its running from the command prompt first.
