### ISSUE TITLE
Different highlighting inside environments

### ISSUE THREAD

**Issue by tdegeus** [LaTeXing/LaTeXing#186]
Hello,

To keep more focus on the main text that I'm writing I would like to change the font (or it's thickness or size or so) inside environments (e.g. of \begin{figure} ... \end{figure}). 

Thanks!
Tom

**Comment by csch0** [comment]
Thats depending on you used Sublime Text theme, please just try a few different and see which suits you the most.

http://colorsublime.com/

**Comment by tdegeus** [comment]
I see. Can you suggest me one that has the described behavior?
