### ISSUE TITLE
Not able to compile .Rnw after update to El Capitan

### ISSUE THREAD

**Issue by md2999** [LaTeXing/LaTeXing#190]
I solved the issue for .tex files by adding "texpath": ["/Library/TeX/texbin"] to the user settings, but unfortunately this did not solve the issue for .Rnw (knitr) files? Any suggestions on what to do? Thanks!

**Comment by hbahamonde** [comment]
Hey @md2999, I had a similar issue: see #192. Do you have ```knitr: true``` set?

**Comment by csch0** [comment]
Thanks @hbahamonde, yes please check that. In 99% of the cases its an configuration problem, perhaps also have a look here http://docs.latexing.com/stable/tutorials/knitr-with-latexing.html

Feel free to reopen the issue in case the problem persists.
