### ISSUE TITLE
Accented OSX paths, utf8 decomposed issue

### ISSUE THREAD

**Issue by juanfal** [LaTeXing/LaTeXing#196]
LaTeXing is unable to build something inside:

    "/Users/me/Documents/Departamento/DOCENCIA/P1-TT/PRÁCTICAS/201415/02.Pract02.tex"'

it seems decomposed UTF8 mac file names doesn't like Python or SublimeText or both.  When the path is sent to the latexmk it receives: PRA'CTICAS  or ba'sico instead of básico.

**Comment by juanfal** [comment]
… for SublimeText is as simple as calling:


    BOOL IsCanonicallyDecompsed(NSString *initialFilePath)

[see here](http://www.hitmaroc.net/1990403-6899-how-determine-whether-nsstring-normalized-nfd.html)  but I don't know why it doesn't do anything at this respect.  Of course every other text editors work perfectly right with decomposed utf filenames.  TextMate never had any class with this.

-

**Comment by csch0** [comment]
It is more latexmk, which cannot be changed from LaTeXing, obvious solution for now would be to remove the accent from the path.

**Comment by juanfal** [comment]
I suppose, I little hacking in latexmk (perl) would help.  Wouldn't it?
