### ISSUE TITLE
Warning message: Latexing is getting old

### ISSUE THREAD

**Issue by tobiasdiez** [LaTeXing/LaTeXing#198]
I constantly get the warning message "Your version is getting old, please update Latexing to the latest available version".
However, I have version 1.2.17 installed which seems to be the latest release. A New-Years bug?  :smile:

**Comment by lblblb** [comment]
Screenshot of the message:
![2016-01-01 13_52_09-sublime text](https://cloud.githubusercontent.com/assets/12690798/12070880/1491624e-b08f-11e5-83df-afee24a6dcaa.png)

**Comment by Dijkstra-ru** [comment]
Same here, changing date to previous year helps (but ruins other things).
Why would you do that?

**Comment by yubow** [comment]
Same here. Could someone help to fix this issue?

**Comment by csch0** [comment]
New Years bug.. :+1: Fixed in 1.2.18, should be available through via package control soon.

**Comment by pfaion** [comment]
I removed Latexing via package control to reinstall it, since this issue would display the message after every character I typed. But now package control does not display latexing anymore for a reinstall. Help please! :D I am writing my thesis atm and have to hand it in on monday... I even paid for latexing!

**Comment by pfaion** [comment]
Ok thanks, version 1.2.18 is now in package control!

**Comment by Dijkstra-ru** [comment]
It is surprising, how many people trying to write thesis at January 1st
hold fast men ୧(⇀︿⇀)ᓄ-¤]═────

**Comment by Alenanno** [comment]
I have two questions (not sure where else to ask):
1. When is Latexing coming back on Package Control? It's not there at the moment.
2. For the manual install, do I just need to move the package file inside the "Installed Packages" folder, and that's it? Because I tried and ST3 was complaining.

**Comment by pfaion** [comment]
I moved the file into "installed packages", then restarted ST3 and executed "Package Control: Install Local Dependency" a couple of times. Although it said "no dependencies" first, after a couple of tries, I got a message "installed x missing dependencies" and then it worked!

**Comment by Alenanno** [comment]
Thank you pfaion. I tried that, said that it had loaded all dependencies but it was doing stuff in console, so I waited, and then I think I restarted it, but in short: it worked. :D

**Comment by tjanpool** [comment]
One thing that a package is getting oud of date, it is attend to inform someone that a package is out of date. It is a bug if you inform someone that something is outdated while it is not. It is however outrages informing someone that something is out of date each keyboard input, what if there is a bug you would not like to do the update. So how should you call informing someone that something is out of date that is not out of date each keyboard input. Please say that this can be fixed by downgrading. Would love that.

**Comment by Hualin** [comment]
where to download latexing???? where is it???  for manual install???

**Comment by egeerardyn** [comment]
@Hualin: Try http://www.latexing.com/installation.html for manual install.

**Comment by Hualin** [comment]
@egeerardyn thank you :D. I am panicking, (mistaken the "ST3 Version" into downloading link for sublime text 3) obviously I am not the only one here who also is writing thesis.

**Comment by PattaFeuFeu** [comment]
Unfortunately, the approach of reinstalling it manually didn’t work for me. I moved the package I downloaded from http://www.latexing.com/installation.html to `~/Library/Application Support/Sublime Text 3/Installed Packages/`and it showed up in ST3 (OSX) but virtually everything in the package’s settings is greyed out—all I can click on is `Settings (Default)` and `Settings (User)`.

When trying to typeset one of the documents that worked last year, the console outputs `Unable to find target command: ltx_default_compiler`.

I tried moving the downloaded .sublime-package file to `~/Library/Application Support/Sublime Text 3/Packages/User/` but that resulted in the package not even being recognised within ST3, even after multiple restarts.

I tried what @Alenanno and @pfaion suggested—installing local dependencies—but even after 10 tries that led to nothing and even after restarting, it’s still the same.

Same as with others, I’m currently writing my thesis and wouldn’t like to change my workflow in the last three weeks of doing so.

**Comment by RAW21** [comment]
Thanks everyone for the comments. I too am writing my thesis and was really scared by this issue. Thanks to @csch0 ! happy new year :+1:

**Comment by pfaion** [comment]
really crazy how many people are writing their thesis at the moment... good luck and hopefully no more issues with latex to you all ;)

**Comment by csch0** [comment]
Looks like there is a problem with package control, see the [twitter account](https://twitter.com/Package_Control). This "bug" is coming from way back where automatic update was not working to ensure people are tipped of to update to the latest version.

A new version is online since 2 days already check the [packages.json](https://csch1.triangulum.uberspace.de/release/packages.json). The problem now is just that package control is not working like expected but you can use the [manual installation](http://www.latexing.com/installation.html) linked above already.

**Comment by lkrcal** [comment]
Exactly the same problem as @PattaFeuFeu. I have deleted Latexing using Package Manager, then installed it manually. No Latexing commands except for the default and user settings, and syntax are available.
![screenshot from 2016-01-03 23 01 53](https://cloud.githubusercontent.com/assets/1066189/12079296/92ae5ab6-b26e-11e5-876a-c47c4f093aa0.png)

**Comment by ada26** [comment]
I also did a manual install on ST3 (OS X El Capitan) and have some problems.  I can still edit my settings though.  I have tried deleting my settings files in ~/Library/Application Support/Sublime Text 3/Packages/User.

When I run quick build, nothing appears to happen.  When I run super+l, super+b, the quick build builds do not appear amongst the available builds either.  I have gotten around this by building from a makefile, but skim does not open the pdf to the part of the pdf I'm currently editing when I compile my thesis.

I don't get autocomplete for citations either.  The sublime command prompt gives an error "Unknown macro command ltx_fill".

**Comment by magnli10** [comment]
Have the same issue as @PattaFeuFeu and @lkrcal. I am no expert but seems to me that uninstalling LaTeXing removed all the dependencies, and the packagecontrol servers are down so they are not installed automatically. The log output hinted at missing dependencies namely tabular and request_oauthlib throwing ImportError. 

I solve tabular by simply adding the github repo manually with package control add repository. As far as I know the request_oauthlib should not even be there? I ended up with a dependency hell trying to get oauthlib to install without package control.

**Comment by nihilon** [comment]
Encountering the same issue as @PattaFeuFeu, @lkrcal, and @magnli10. Encountered this same error, and then did the following variant of steps identified in one of the other related issues here:

1. Remove LaTeXing via PC
2. Check to ensure that oauth references in PC's settings do not exist. I also made sure that the package itself does not exist anywhere
3. Exit ST3
4. Manually installed LaTeXing
5. Started ST3

Seeing the following on the console:

**In startup after manual install (from http://www.latexing.com/installation.html):**

reloading plugin LaTeXing.LaTeXing
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "LaTeXing in C:\Users\UserName\AppData\Roaming\Sublime Text 3\Installed Packages\LaTeXing.sublime-package", line 4, in <module>
  File "/Development/latexing/__init__.py", line 15, in <module>
  File "/Development/latexing/check_system.py", line 5, in <module>
ImportError: No module named 'tabulate'
...
Package Control: Installing 4 missing dependencies
Package Control: The dependency specified, tabulate, is not available
Package Control: The dependency specified, requests, is not available
Package Control: The dependency specified, oauthlib, is not available
Package Control: The dependency specified, requests-oauthlib, is not available
Package Control: Skipping automatic upgrade, last run at 2016-01-03 20:46:15, next run at 2016-01-03 21:46:15 or after

**Package Control: Satisfy Dependencies**

Package Control: The dependency requests is not currently installed; installing
Package Control: The dependency specified, requests, is not available
Package Control: The dependency requests could not be installed or updated
Package Control: The dependency requests has successfully been installed or updated
Package Control: The dependency requests-oauthlib is not currently installed; installing
Package Control: The dependency specified, requests-oauthlib, is not available
Package Control: The dependency requests-oauthlib could not be installed or updated
Package Control: The dependency requests-oauthlib has successfully been installed or updated
Package Control: The dependency tabulate is not currently installed; installing
Package Control: The dependency specified, tabulate, is not available
Package Control: The dependency tabulate could not be installed or updated
Package Control: The dependency tabulate has successfully been installed or updated
error: Package Control

One or more dependencies could not be installed or updated.

Please check the console for details.

**After adding tabulate as a repository**

reloading plugin LaTeXing.LaTeXing
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "LaTeXing in C:\Users\UserName\AppData\Roaming\Sublime Text 3\Installed Packages\LaTeXing.sublime-package", line 4, in <module>
  File "/Development/latexing/__init__.py", line 17, in <module>
  File "/Development/latexing/cache.py", line 19, in <module>
  File "/Development/latexing/api/mendeley.py", line 9, in <module>
ImportError: No module named 'requests_oauthlib'
...
Package Control: Installing 4 missing dependencies
Package Control: The dependency specified, requests, is not available
Package Control: The dependency specified, requests-oauthlib, is not available
Exception in thread Thread-3:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "package_control.automatic_upgrader in C:\Users\UserName\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 113, in run
  File "package_control.automatic_upgrader in C:\Users\UserName\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 145, in install_missing
  File "package_control.package_manager in C:\Users\UserName\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 1317, in install_package
KeyError: 'load_order'

Additionally, I feel it is worth noting that in the PC cache and in dependencies.json in the LaTeXing package, after downloading the current one from the noted URL, the oauth dependencies are still being listed. Removing them from the dependencies json in the LaTeXing package manually had no apparent effect.

Any ideas would be great.

**Comment by tobiasdiez** [comment]
What worked for me was the following:
1. Do *not* remove Latexing from Package Control
2. Download the new version of Latexing from http://www.latexing.com/installation.html (you get a LaTeXing.sublime-package file)
3. Replace the original LaTeXing.sublime-package in `AppData\Roaming\Sublime Text 3\Installed Packages` (path depends on Os) with the just downloaded one.
4. Happy Latexing

**Comment by tobiasdiez** [comment]
The new version 1.2.18 is now available through package control and works perfectly. Thanks for the quick fix!

**Comment by okvs** [comment]
I have version 1.2.17 and Package Control tells me that

> There are no packages ready for upgrade

Is this a sublime bug or has the newest version gone missing? According to [http://www.latexing.com/](url) the latest version is _1.2.16_

**Comment by QuentinRoy** [comment]
I got this again. Is it going to happen every year?

**Comment by giannigdev** [comment]
I have the same problem: 
![1](https://cloud.githubusercontent.com/assets/4886490/21581335/938e21d0-d02e-11e6-95bf-03029d08f7a7.png)

is this a problem with LaTeXing or with Sublime Text??

**Comment by leekh3** [comment]
Same Issue again....

**Comment by chrismeserole** [comment]
I just had the same issue. I followed the four steps @tobiasdiez mentioned above and that solved the problem. (Using El Capitan 10.11.6 and ST3 Build 3126.)

**Comment by CarloNicolini** [comment]
On Ubuntu fixed via manual installation.
Waiting for the packaged version, that is still not recognized.

**Comment by afcuttin** [comment]
Sorry to say to reopen, but this still happens today

**Comment by afcuttin** [comment]
and this is no longer available:

> 2\. Download the new version of Latexing from http://www.latexing.com/installation.html (you get a LaTeXing.sublime-package file)

**Comment by vkrao100** [comment]
yup, history repeats !! anyone has a working solution?

**Comment by jack793** [comment]
CMON

**Comment by jlidbeck** [comment]
Same issue: update popup with each keypress, updating package through standard means doesn't work.

This was a suitable replacement for my needs:
https://github.com/SublimeText/LaTeXTools

**Comment by ShrykeWindgrace** [comment]
PSA: this plugin is all but abandoned.
