### ISSUE TITLE
"Your version is getting old, please update LaTeXing to the latest available version.", but no new version is available.

### ISSUE THREAD

**Issue by mightytarzan** [LaTeXing/LaTeXing#199]
Since January 1st, 2016 LaTeXing 1.2.17 (running on Linux) repeatedly opens a popup dialog which instructs me to update to the newest version. However, no new version is available according to package control.

**Comment by shiguera** [comment]
Same here

**Comment by yubow** [comment]
Same here. Could someone help to fix this issue?

**Comment by csch0** [comment]
see #198
