### ISSUE TITLE
Refresh Zotero/online libraries?

### ISSUE THREAD

**Issue by dillonma** [LaTeXing/LaTeXing#202]
I know this was coming and hopefully it's already implemented, but I can't find a command to actually force a refresh of the zotero library? Did I miss it or is this actually a feature request?

**Comment by drevicko** [comment]
Yes, you missed it: 
  cmd-shift-P  -  to get the command pallette
then:
  LateXing Synchronise Remote Data

this will update the Zotero cache. If you then build, you'll be asked to update your bib file.

**Comment by dillonma** [comment]
Brilliant.
