### ISSUE TITLE
Feature request: sort bib file by year and then title

### ISSUE THREAD

**Issue by simonzack** [LaTeXing/LaTeXing#207]
Can there be a way of sorting the `.bib` file, possibly by year and then title? My bib file is a huge mess right now and it would be great to have it organized.

**Comment by egeerardyn** [comment]
I suppose there are other and better tools for that: http://unix.stackexchange.com/questions/31266/how-to-sort-by-whatever-key-bibtex-entries-in-bib-file .
Also, if you use a program specifically for managing BIB files, you can get such results for free: e.g. I use JabRef. It's far from the best, most beautiful or most powerful tool, but it automatically takes care of such details for you. So any half-decent BIB editing tool will probably be an improvement over editing the file by hand.

**Comment by simonzack** [comment]
Good point, I should just keep on using zotero for this. I found this plugin which doesn't exactly sort things but does keep the order deterministic: http://zotplus.github.io/zotero-better-bibtex/index.html.
