### ISSUE TITLE
Partial Build

### ISSUE THREAD

**Issue by TrevorRempel** [LaTeXing/LaTeXing#215]
I am currently working with a large project spread over multiple files. I am using the subfiles package and have enabled partial_build. However, when I build one of the subfiles it will compile and show only the root document.

**Comment by csch0** [comment]
That's working for sure, heavily used it in the past, could you provide a minimal non working example at info@latexing.com.

**Comment by TrevorRempel** [comment]
After some fiddling I figured out what the problem was. Suppose I have two files my main one main.tex and a single subfile file1.tex. If I work on file1 and then switch to main and compile it will compile and build file1.tex. To get it to compile main.tex I have to make a change to that file.
