### ISSUE TITLE
License problem after a certain time

### ISSUE THREAD

**Issue by FriedlTheFox** [LaTeXing/LaTeXing#225]
Hello,

I'm using LaTeXing with a license but after a certain time the license dialog will pop up. If I close Sublime and open it again, all is working fine. License was installed over the menu and the license file.

Do you have a solution or hint for me?

Thank you.
Bye,
Friedl

PS: Windows 7, Sublime 3 (build 3114) and LaTeXing 1.2.19 is in use.

**Comment by csch0** [comment]
That's not normal. Please sent an email for info@latexing.com

**Comment by FriedlTheFox** [comment]
Check the mail adress, it is case sensitive!
This hint solved the problem.

Thank you.
Bye,
Friedl
