### ISSUE TITLE
Not on packagecontrol.io

### ISSUE THREAD

**Issue by sinqbad** [LaTeXing/LaTeXing#266]
Tried installing this through sublime and there's no package called "LaTeXing" and when I go to packagecontrol.io it says the package is missing.

**Comment by jarq6c** [comment]
latexing.com is down as well. I guess for $15 USD it was good while it lasted?

**Comment by csch0** [comment]
Even better @jarq6c I made it open source so everybody can contribute and so hopefully the extension will become even stronger.

Agree the links are not updated, will have to do it.

**Comment by nbrewk** [comment]
Forgive me if there is an obvious answer, but is there a workaround in the meantime?

**Comment by jarq6c** [comment]
@nbrewk It looks like the La​Te​XTools package has matured significantly and is available using Package Control. The settings are very similar to La​Te​Xing. So far, La​Te​XTools seems to include all the features that initially drew me to La​Te​Xing.

**Comment by csch0** [comment]
Should be available again today or tomorrow, made all the pull request.

@jarq6c You are welcome to contribute also to LaTeXing, thats why I made it open source since I have not that much time anymore.

Anyway even if it just brought LaTeXTools in better light I made a good job. 👍

**Comment by ritou11** [comment]
Oops... I still cannot find it by PackageControl. Any ideas?

**Comment by sinqbad** [comment]
@ritou11 I checked today and it's there for me.

**Comment by ritou11** [comment]
@sinqbad Thx. It seems ready today.
