### ISSUE TITLE
Your version is getting old, please update LaTexing to latest available version 

### ISSUE THREAD

**Issue by xqian777** [LaTeXing/LaTeXing#270]
I don't know how to update this, already try to find the Latexing, but canot find in the packages, now, I cannot use sublime.

<img width="419" alt="screen shot 2019-01-02 at 2 49 03 pm" src="https://user-images.githubusercontent.com/41385387/50582470-bf152880-0e9d-11e9-8e3b-f09fc55c5f81.png">

**Comment by hmshan** [comment]
This bug seems to happen every new year. I am also waiting for new updates.

**Comment by xqian777** [comment]
I think you can try to delete the Latexing package, and then re-install again. I fixed it by this way.

**Comment by hmshan** [comment]
I think i ran into the same problem that i can't find it in my package control. How did you re-install it?

**Comment by drevicko** [comment]
@xqian777 if you've solved this, perhaps you should close the issue..
