### ISSUE TITLE
Licensing Options

### ISSUE THREAD

**Issue by diego898** [LaTeXing/LaTeXing#50]
Hello,

I am trying out latexing and after 15 minutes of use the popup is every single time I build. To make maters worse, I cant even purchase a license right now! Do you have some way of disabling this while licensing is disabled? 

Thank you!

**Comment by diego898** [comment]
@csch0 Just checking back on this? Im still getting the popup very very frequently.

**Comment by Gabriel-p** [comment]
@diego898 please see #59. He's not interested in fixing/changing this. Cheers.
