### ISSUE TITLE
Pop up window asking to buy is relentless

### ISSUE THREAD

**Issue by Gabriel-p** [LaTeXing/LaTeXing#59]
I'm sorry to bring this up again but I would like to know if there are any intentions in reducing the frequency with which the pop-up appears.

In a normal day of using Sublime to edit a LaTeX file the pop-up appears _no less than two dozen times_. It also has the annoying habit of popping every time the file is not edited for a couple of minutes with the _Accept_ button selected by default, which means it will block any keyboard stroke until you realize that you've inadvertently hit the button and the package opened a new tab in your browser.

**Comment by adrianogil** [comment]
It's indeed a serious issue. I'm also moving to another plugin!

**Comment by diego898** [comment]
Even though I ended up purchasing, I have also moved to LatexTools. This plugin doesn't have the support or activity I have come to expect from paid software.
