### ISSUE TITLE
Mendeley import

### ISSUE THREAD

**Issue by rudvfaden** [LaTeXing/LaTeXing#66]
Some bugs in the Mendeley BibTeX import.

1. Not all characters are correctly escaped. E.g. è is **not** changed to ```\`{e}```
2. Some long journal names are shortened. E.g. `Journal of Economics \& Management Strategy` are shortened to `Journal of Economics \& ...`

**Comment by csch0** [comment]
Is this still a problem with the use of the new Mendeley API?

**Comment by rudvfaden** [comment]
Yes. But no the journal field is completely missing.

**Comment by csch0** [comment]
Lets stick to this issue first and then open a new one for issues related to the API.

**Comment by csch0** [comment]
#105 is still open for issues, and should fix this in the next release version.
