### ISSUE TITLE
LaTeXing cannot find latexmk

### ISSUE THREAD

**Issue by max-prime-math** [LaTeXing/LaTeXing#69]
When I build a .tex file it gives me a message saying:

```
[Compile /path/to/my/file.tex]
Unexpected error in log file!
1 error, 0 warnings, 0 badboxes
[Finished in 0.17s]
```

The problem is that it doesn't seem to generate a log file at all!  When I check my system (`LaTeXing: Check System`) it tells me that it cannot find `latexmk` (all other dependencies are okay) and it tells me to look at LaTeX.sublime-build.  When I do, I have the following line: `"path": "$PATH:/usr/texbin:/usr/local/bin:/opt/local/bin"`, which should be correct, since my latexmk perl file is in /usr/texbin.

At a loss here.  Can anyone help?

**Comment by arvindr9** [comment]
I had a similar error except that Path version 1.08 was required. I changed that part of the code from 2.08 to 1.08, but now I get this error:

make_path" is not exported by the File::Path module
Can't continue after import errors at C:\Program Files\MiKTeX 2.9\scripts\latexmk\latexmk.pl line 157
BEGIN failed--compilation aborted at C:\Program Files\MiKTeX 2.9\scripts\latexmk\latexmk.pl line 157.

Does anyone have ideas on how I can proceed? Thanks!
