### ISSUE TITLE
License key in separate settings file?

### ISSUE THREAD

**Issue by bcomnes** [LaTeXing/LaTeXing#79]
Hi!  I like to publish my sublime text settings to a public repo, but I can't do that now because there is a license key in my LaTeXing settings file.

Is it possible to store that license in a separate settings file so that I can keep my latexing settings checked into version control and publish those settings publicly (while adding the license file to my ignore list)?

**Comment by bcomnes** [comment]
Any update on this?  Really would love to stop wasting a private github repo on my sublime settings just because of the LaTeXing license.  If you don't have time, do you have any pointers on how you would like this done for a PR?

**Comment by N4M3Z** [comment]
Simply moving the license information into a file like LaTeXing.sublime-license (the way Sublimerge package does it) seems a reasonable solution to me.

**Comment by csch0** [comment]
Yes already done that. Will push the new version later tonight.

**Comment by bcomnes** [comment]
Sweet!  Glad to hear it :+1:   Thankyou

**Comment by csch0** [comment]
Added in 1.2.9

**Comment by bcomnes** [comment]
Can you confirm the location of where this LaTeXing.sublime-license lives? (ST3 Settings Folder/Local ?)

**Comment by csch0** [comment]
at the moment its inside the user folder?! Do you think it would make more sense outside this folder and place it in Local like you mentioned?

**Comment by bcomnes** [comment]
Doesn't matter to me, as long as its described somewhere.  Can you describe how to create and use the external license file? I can't figure it out.

**Comment by csch0** [comment]
Normally it should be just a LaTeXing.sublime-license in your user folder. You could please check the latest testing version, it should extract the information automatically now. :) Once the Mendeley issues are resolved this will be included in the normal release.

**Comment by bcomnes** [comment]
Should it just be JSON formatted like settings file?  The only reason I ask is that the sublime licence file is formatted differently despite having the same file extension.

**Comment by csch0** [comment]
Yes!

**Comment by bcomnes** [comment]
Cool!  Thanks for doing this.

**Comment by N4M3Z** [comment]
This does not seem to work for me. I simply added `LaTeXing.sublime-license` file into my user folder (`.../Sublime Text 3/Packages/User/`) which includes the following:
```
{
	"username": "<myusername>",
	"license": "<mylicense>",
}
```

However, I am still getting the "unregistered version" warnings.

**Comment by csch0** [comment]
With the latest testing version??

**Comment by N4M3Z** [comment]
1.2.9. upgraded through Package Control

**Comment by csch0** [comment]
So could you please check the latest testing version. It's almost identical.

**Comment by N4M3Z** [comment]
Sorry, confused. How can I get it?

**Comment by csch0** [comment]
@N4M3Z Have a look here: http://docs.latexing.com/stable/introduction.html#testing-version

**Comment by N4M3Z** [comment]
Thank you, all is well now. Sorry for the false alarm. 

However, now that I was about to upload my LaTeXing settings to GitHub, I realized that `LaTeXing.sublime-settings` file still does contain other sensitive information like `citeulike_username` ,`mendeley_oauth_token` etc. So at least on my side, this means I still have to use encryption. Perhaps these entries should be moved as well?

**Comment by csch0** [comment]
If we start this then pretty much everything has to move. So I guess the best option would be to encrypt the settings itself or? But normally don't like this idea?! Any other suggestions?

**Comment by csch0** [comment]
And you have the same for every package where you save something confidential.

Perhaps try this https://github.com/csch0/SublimeText-Package-Syncing

**Comment by N4M3Z** [comment]
Yes, you are of course right, that this is a problem with any package that contains sensitive data. I am encrypting those files using blackbox (https://github.com/StackExchange/blackbox) as well as using PackageSyncing to backup my settings. Apart from this, I don't have any good ideas on how to approach this.

**Comment by csch0** [comment]
For me Package Syncing was always enough, that's why I programmed it. :)
