### ISSUE TITLE
Foxit Reader default path incorrect

### ISSUE THREAD

**Issue by Kaba2** [LaTeXing/LaTeXing#83]
The default path to Foxit Reader is currently "C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\Foxit Reader.exe", which is incorrect. This prevents the Foxit Reader from opening. The correct path is to FoxitReader.exe, without the space. The problem is easy to fix to specifying the correct path in the user settings.

**Comment by csch0** [comment]
Thanks!

**Comment by csch0** [comment]
Fixed in 1.2.9
