### ISSUE TITLE
Unable to open Packages/LaTeXing/LaTeX.sublime-build

### ISSUE THREAD

**Issue by lmoffereins** [LaTeXing/LaTeXing#85]
Just installed the latest version of TexLive 2014 (for better LaTeXing support) and LaTeXing in ST3 on Win8. In order to have a correct System Check, directing LaTeXing to TexLive in the sublime-build file should do the trick, since the default value for the Windows `path` setting directs to MikTeX. Yet, when trying to edit the `.sublime-build` file (Settings Extended), there's no editing possible (adding or removing text) in the file. The file contents are on the screen, but that's all. Additionally the console throwed an `Unable to open /C/Users/xxx/AppData/Roaming/Sublime Text 3/Packages/LaTeXing/LaTeX.sublime-build` error. Running ST3 as admin doesn't help either. 

Any idea what might be going on?

**Comment by csch0** [comment]
Mmm.. I think this is more ST issue or misinterpretation of the error message. So what you have to do here is to copy the default file to your user directory by doing the following:

1. Preferences: LaTeXing Settings - Default (Extended) > Open the *sublime-build
2. Preferences: LaTeXing Settings - User (Extended) > Open the *sublime-build

Copy the content from the default into the user file and save it. Adjust the path as you like afterwards.

**Comment by sunew** [comment]
There is no 
Preferences: LaTeXing Settings - User (Extended) > Open the *sublime-build
in my installation? 
Latexing 1.2.4

I had to manually copy the build file to the user package, but then there are two build systems with the same name shoing up in the build menu.

**Comment by oozaru-hunter** [comment]
I may have a similar problem. I installed today Latexing via the Package manager (1.2.8).
OS is Debian Wheezy with ST3 (3065).
Under Packge Settings -> Latexing  most of the entries are greyed out. 
I can only click on Settings User and Default, and on the keybindings.

There is no LaTeXing folder in .config/sublime-text-3/Packages!

**Comment by lmoffereins** [comment]
For my taste, removing and reinstalling LaTeXing as well as some restarting ST solved the issue. Had some more trouble starting off as a LaTeX first-timer, but I'm all good now.
