### ISSUE TITLE
Continue within itemize environment

### ISSUE THREAD

**Issue by kfinlay** [LaTeXing/LaTeXing#92]
Suppose you're in an itemize (etc.) environment and you want to continue the n^th \item. Is it possible to, say, do CMD-ENTER to auto-start the next line with \item? Thanks very much for your help.

**Comment by aeonstone** [comment]
While something like this would be great there is a pretty easy work around that I have been using. You can create a custom completions file for latex documents ... maybe you already have one.? In this file I create a couple of custom commands to make these listing environments much easier. Just type the trigger and hit tab to auto insert the commands I want. Once I am done with an item I hit enter, then "i" followed by a quick "tab" this substitutes to \item followed by a space so I am ready to keep on keeping on.

                { "trigger": "bit", "contents": "\\begin{itemize}\n\t\\item $1 \n\\end{itemize}\n"},
                { "trigger": "ben", "contents": "\\begin{enumerate}\n\t\\item $1 \n\\end{enumerate}\n"},
                { "trigger": "i", "contents": "\\item "},

**Comment by csch0** [comment]
Oh just recovered this issue @kfinlay and you can do that with shift+enter or is this not working for you?

**Comment by kfinlay** [comment]
Aha! Shift-enter works. Sorry for the tech-support-type question. Thanks @aeonstone also. Those completions look handy.
