### ISSUE TITLE
build arguments

### ISSUE THREAD

**Issue by vogler** [LaTeXing/LaTeXing#93]
Using `minted` I need `-shell-escape` for the build.
Appending the arguments in `cmds` for the quick build doesn't work. I also edited `LaTeX.sublime-build` without any effects.

**Comment by csch0** [comment]
As an additional build argument it should work.

http://docs.latexing.com/stable/settings.html#additional-build-arguments

**Comment by vogler** [comment]
Sorry, found `build_arguments`.

**Comment by keven425** [comment]
I'm running into this same issue. This is my user settings:

```
{
	"typeset_on_save": true,
	"build_arguments": ["-shell-escape"]
}
```

However, I still get this error:
```
....tex:9 Package minted Error: You must invoke LaTeX with the -shell-escape flag \usepackage
```

Am I missing something?
