### ISSUE TITLE
Cannot access Mendeley.com

### ISSUE THREAD

**Issue by magnli10** [LaTeXing/LaTeXing#94]
Hello,
I had major issues with the local bib not syncronizing with mendeley.com. It would always return the message that everything is up to date when trying to import newly added articles. Note the first import worked like a charm.
In an attempt to fix the issue I set the `"cache": { "mendeley": 0 }`. 
Now I get
> Cannot access Mendeley.com, please check docs.latexing.com for more details. 

I could not find any information in the docs about troubleshooting api access. Tried resubscribing to the mendeley api but still have the same issue.

I use Latexing 1.2.4 and ST build 3065

**Comment by adamaltmejd** [comment]
Same here!

**Comment by mikeoconnor0308** [comment]
This is affecting me too, main feature for me!

**Comment by csch0** [comment]
Working on this right now. A new testing version should be available tonight, if you would like to take part of the testing process stay tuned.

**Comment by csch0** [comment]
OK testing version is online, just have a look and give some feedback 

http://testing.latexing.com/packages.json

The API changed a lot so needs to be tested.

**Comment by csch0** [comment]
Please make sure you enabled the "install_prereleases" of package control (https://packagecontrol.io/docs/settings). Check the version number after updating... should be 1.2.5-rc.1

**Comment by magnli10** [comment]
This fixed the import issue for me, thanks! My version check says 1.2.3 even though the package control says 1.2.5-rc1 when i did the upgrade. 

For others, like me, who are new to the sublime package control you can simply put this 
`{ "install_prereleases": ["LaTeXing"] , "repositories": ["http://testing.latexing.com/packages.json"] } `
in your `Package Control.sublime-settings` file, then run `package control upgrade`.

**Comment by pujan14** [comment]
This fixed import issue but there are some new issues. There is no book title/journal name field, also there are now two fields issn and isbn both containing exactly same data. For me main issue is lack of book title/journal name

**Comment by csch0** [comment]
Yes thats possible, like I said API changed a lot and need much more testings to be stable.

**Comment by csch0** [comment]
Any further problems found?

**Comment by pujan14** [comment]
I didn’t notice any other issues.

**Comment by adamaltmejd** [comment]
Works for me too!

**Comment by minihessel** [comment]
Nice, will there be a new version really soon then?

**Comment by csch0** [comment]
Sure

**Comment by minihessel** [comment]
Great, have a lot of comments that basically say %cite xxx here % :)

**Comment by minihessel** [comment]
Still can't see a new version, any update Chris? :)

**Comment by csch0** [comment]
Had to address one other issue with a different user over the weekend. Solved this and will push a new version tonight. Thanks. :)

**Comment by minihessel** [comment]
A, great! Have so many %cite here% comments now, haha.

2015-02-23 8:48 GMT+01:00 csch0 <notifications@github.com>:

> Had to address one other issue with a different user over the weekend.
> Solved this and will push a new version tonight. Thanks. :)
>
>
>
> > On 23 Feb 2015, at 08:44, minihessel <notifications@github.com> wrote:
> >
> > Still can't see a new version, any update Chris? :)
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LaTeXing/LaTeXing/issues/94#issuecomment-75500658>.
>



-- 
_____________________________
Med vennlig hilsen Eskil
www.eskil-hesselroth.com

**Comment by minihessel** [comment]
![screen shot 2015-02-24 at 08 40 00](https://cloud.githubusercontent.com/assets/5398823/6345158/a7e8390a-bc02-11e4-9bda-1c5644acdbe7.png)

New version throws you to localhost, and the key parsed in the URL isn't valid. 

Mentally writes about how to parse this here : http://dev.mendeley.com/reference/topics/authorization_implicit.html

**Comment by csch0** [comment]
Mm ok then a new fix will come tonight. :)

**Comment by csch0** [comment]
OK I think there is a problem with the Mendeley service. It was definitely working last week, dropped them an Email and will keep you updated asap.

**Comment by minihessel** [comment]
Any updates? I really need this citation function, I'm sorry!

**Comment by csch0** [comment]
Yes I am also sorry about that. The testing version was working last week and now it looks like Mendeley changed something. Cannot do more than working on it and talk to the support as well.

**Comment by minihessel** [comment]
I understand, will be watching the thread for updates. Cheering on you!

**Comment by minihessel** [comment]
Did Mendely answer you? They never answered me when asking about it.

**Comment by csch0** [comment]
Nope not so far, but seriously working on it. Should be a fix before the weekend. I am really sorry for this!

**Comment by minihessel** [comment]
Ah, nice with a fix before the weekend. No problem :)

**Comment by mikeoconnor0308** [comment]
Seems to be working for me now? Thanks for all your hard work on this.

**Comment by minihessel** [comment]
Perhaps because your Mendely already is authorised ? If you remove the oath token, you won't be able to authorise Latexing again.

**Comment by minihessel** [comment]
![screen shot 2015-02-27 at 16 09 37](https://cloud.githubusercontent.com/assets/5398823/6414860/152792dc-be9b-11e4-8c97-39cb3831bbf8.png)
Finally got a hold of Mendeley, they will be answering you ASAP @csch0

**Comment by csch0** [comment]
Thanks @minihessel I also got a response today which is saying:

> @David do you mind replying to this, I've let it drop. 
>
> Thanks

Great support so far ^^ we will see.

**Comment by minihessel** [comment]
Haha, seriously? Guess a "fix" won't be available that soon after all, since they can't even provide support for their API :/

**Comment by csch0** [comment]
Don't worry, will be fixed soon. Found a way around it, just needed to reimplement the oauth2 in LaTeXing.

**Comment by minihessel** [comment]
Okey, cheers for you !

**Comment by minihessel** [comment]
Real close now @csch0 , the auth page works, just not the code :P

**Comment by csch0** [comment]
Yes.. really close. :) Thanks

**Comment by minihessel** [comment]
Just wanted to say that I truly appreciate all the time you put down in this @csch0 . A thank you from me! *purchase coffee for @csch0 *

**Comment by csch0** [comment]
Ok, so I think everything is online now. Steps you need to do @minihessel to make me happy :)

0.) Remove the old oauthlib package, its working slightly different now.
1.) Make sure you are using the latest package control version (v3.0.1)
2.) Please add to package control add simply add this:
```javascript    
{ 
    "install_prereleases": ["LaTeXing"] ,
    "repositories": ["http://testing.latexing.com/packages.json"] 
} 
```
3.) Install LaTeXing (should be 1.2.7-rc1)
4.) Wait for package control and restart Sublime Text
5.) Give it a go.. hopefully it will work. :)

**Comment by minihessel** [comment]
Okay, i believe it works ! :dancers:  

Couple of questions:
1. Did LateXing install a newer version of oathlib? 
2. So this is a beta, and it will be released official in the next couple of days?

**Comment by csch0** [comment]
Yes latexing is using a function of package control to define common libraries. It's a more elegant ways since you don't have to install multiple packages manually.

Yes will be released tonight as stable the.

**Comment by minihessel** [comment]
Will be testing for some hours :)

**Comment by minihessel** [comment]
Report: it works great.

**Comment by csch0** [comment]
Thanks for the feedback and its stable now in 1.2.8.

**Comment by minihessel** [comment]
Cheers for @csch0 !
