### ISSUE TITLE
Annoying mnemonic message

### ISSUE THREAD

**Issue by FichteFoll** [LaTeXing/LaTeXing#95]
Since 3067, ST prints warnings for menu items where the mnemonic is not found in the name, which gets pretty annoying since it is printed whenever the package files are re-indexed.

You have to change that to an upper case "L".

```
warning: mnemonic l not found in menu caption LaTeXing
```

**Comment by csch0** [comment]
Thanks @FichteFoll, just checking/fixing it.

**Comment by csch0** [comment]
Will come with the next version (tonight).
